name = "StipplePlotly"
uuid = "ec984513-233d-481d-95b0-a3b58b97af2b"
authors = ["Adrian <e@essenciary.com> and contributors"]
version = "0.5"

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
Stipple = "4acbeb90-81a0-11ea-1966-bdaff8155998"

[compat]
Genie = "2, 3"
Stipple = "0.13, 0.14, 0.15"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
