site_name:        StipplePlotly.jl
repo_url:         https://github.com/GenieFramework/StipplePlotly.jl
site_description: Plottly library for Stipple.jl
site_author:      Adrian Salceanu

theme: readthedocs

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
